-- ============================================
-- MIGRACIÓN COMPLETA - BOOM! 2026
-- Este script configura toda la base de datos
-- ============================================

-- 1. TABLA PRINCIPAL DE VENTAS
CREATE TABLE IF NOT EXISTS boom_sales_2026 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    dni TEXT,
    ticket_name TEXT NOT NULL,
    ticket_price NUMERIC DEFAULT 0,
    quantity INTEGER DEFAULT 1,
    total_amount NUMERIC DEFAULT 0,
    payment_method TEXT DEFAULT 'yape',
    payment_proof TEXT,
    status TEXT DEFAULT 'pending',
    approved_at TIMESTAMPTZ,
    approved_by TEXT,
    rejection_reason TEXT,
    attendees TEXT,
    checked_in BOOLEAN DEFAULT FALSE,
    checked_in_at TIMESTAMPTZ
);

-- 2. TABLA PARA LINEUP (Géneros musicales)
CREATE TABLE IF NOT EXISTS boom_lineup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    genre_subtitle TEXT,
    description TEXT,
    video_url TEXT,
    icon_name TEXT,
    color_gradient TEXT,
    display_order INTEGER DEFAULT 0
);

-- 3. TABLA PARA GALERÍA
CREATE TABLE IF NOT EXISTS boom_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT,
    image_url TEXT NOT NULL,
    media_type TEXT DEFAULT 'image',
    display_order INTEGER DEFAULT 0
);

-- 4. ÍNDICES PARA OPTIMIZACIÓN
CREATE INDEX IF NOT EXISTS idx_sales_status ON boom_sales_2026(status);
CREATE INDEX IF NOT EXISTS idx_sales_created_at ON boom_sales_2026(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_email ON boom_sales_2026(email);

-- 5. POLÍTICAS DE SEGURIDAD (RLS)
ALTER TABLE boom_sales_2026 ENABLE ROW LEVEL SECURITY;
ALTER TABLE boom_lineup ENABLE ROW LEVEL SECURITY;
ALTER TABLE boom_gallery ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas antiguas si existen
DROP POLICY IF EXISTS "Public Read Sales" ON boom_sales_2026;
DROP POLICY IF EXISTS "Public Insert Sales" ON boom_sales_2026;
DROP POLICY IF EXISTS "Admin All Sales" ON boom_sales_2026;
DROP POLICY IF EXISTS "Public Read Lineup" ON boom_lineup;
DROP POLICY IF EXISTS "Public Read Gallery" ON boom_gallery;
DROP POLICY IF EXISTS "Admin All Lineup" ON boom_lineup;
DROP POLICY IF EXISTS "Admin All Gallery" ON boom_gallery;

-- Crear políticas nuevas
CREATE POLICY "Public Read Sales" ON boom_sales_2026 FOR SELECT USING (true);
CREATE POLICY "Public Insert Sales" ON boom_sales_2026 FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin All Sales" ON boom_sales_2026 USING (true) WITH CHECK (true);

CREATE POLICY "Public Read Lineup" ON boom_lineup FOR SELECT USING (true);
CREATE POLICY "Public Read Gallery" ON boom_gallery FOR SELECT USING (true);
CREATE POLICY "Admin All Lineup" ON boom_lineup USING (true) WITH CHECK (true);
CREATE POLICY "Admin All Gallery" ON boom_gallery USING (true) WITH CHECK (true);

-- 6. DATOS INICIALES LINEUP
TRUNCATE TABLE boom_lineup RESTART IDENTITY;

INSERT INTO boom_lineup (name, genre_subtitle, description, icon_name, color_gradient, display_order) VALUES
('CUMBIA PERUANA', 'Cumbia / Tropical', 'Los mejores éxitos de cumbia que harán bailar a todos.', 'Music', 'from-green-500 to-emerald-600', 1),
('HUAYNO & FOLKLORE', 'Música Andina', 'El ritmo de los Andes que nos representa.', 'Mic2', 'from-red-500 to-orange-600', 2),
('REGGAETON', 'Urbano Latino', 'Los hits más candentes del reggaeton internacional.', 'Headphones', 'from-neon-pink to-purple-600', 3),
('SALSA & MERENGUE', 'Tropical Latino', 'Sabor latino para bailar sin parar.', 'Sparkles', 'from-yellow-500 to-amber-600', 4),
('ELECTRÓNICA', 'EDM / House', 'Beats electrónicos para elevar la energía.', 'Zap', 'from-blue-500 to-cyan-600', 5),
('ROCK EN ESPAÑOL', 'Rock Latino', 'Clásicos del rock que todos cantamos.', 'Radio', 'from-purple-500 to-pink-600', 6),
('MÚSICA ROMÁNTICA', 'Baladas / Pop', 'Las canciones que enamoran y emocionan.', 'Disc', 'from-orange-500 to-red-600', 7),
('FIESTA RETRO', 'Clásicos 80s-90s', 'Los éxitos que marcaron generaciones.', 'Sparkles', 'from-pink-500 to-rose-600', 8);

-- 7. STORAGE BUCKET PARA CONTENIDO
INSERT INTO storage.buckets (id, name, public) 
VALUES ('content', 'content', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de Storage
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload" ON storage.objects;
DROP POLICY IF EXISTS "Public Update" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'content' );
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'content' );
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING ( bucket_id = 'content' );
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING ( bucket_id = 'content' );
