-- ============================================
-- MÓDULO DE VENTA DE BEBIDAS - BOOM! 2026
-- Sistema de punto de venta para licores y cocteles
-- ============================================

-- 1. TABLA DE PRODUCTOS (Licores y Cocteles)
CREATE TABLE IF NOT EXISTS boom_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- 'licor', 'coctel', 'cerveza', 'shot', etc.
    price NUMERIC NOT NULL DEFAULT 0,
    image_url TEXT,
    stock INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    description TEXT
);

-- 2. TABLA DE VENTAS DE BEBIDAS
CREATE TABLE IF NOT EXISTS boom_drink_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    product_id BIGINT REFERENCES boom_products(id),
    product_name TEXT NOT NULL, -- Denormalized for history
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL DEFAULT 0,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    sold_by TEXT DEFAULT 'admin',
    notes TEXT
);

-- 3. ÍNDICES PARA OPTIMIZACIÓN
CREATE INDEX IF NOT EXISTS idx_products_category ON boom_products(category);
CREATE INDEX IF NOT EXISTS idx_products_active ON boom_products(active);
CREATE INDEX IF NOT EXISTS idx_drink_sales_created ON boom_drink_sales(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drink_sales_product ON boom_drink_sales(product_id);

-- 4. POLÍTICAS DE SEGURIDAD (RLS)
ALTER TABLE boom_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE boom_drink_sales ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas antiguas si existen
DROP POLICY IF EXISTS "Public Read Products" ON boom_products;
DROP POLICY IF EXISTS "Admin All Products" ON boom_products;
DROP POLICY IF EXISTS "Public Read Drink Sales" ON boom_drink_sales;
DROP POLICY IF EXISTS "Admin All Drink Sales" ON boom_drink_sales;

-- Crear políticas nuevas
CREATE POLICY "Public Read Products" ON boom_products FOR SELECT USING (active = true);
CREATE POLICY "Admin All Products" ON boom_products USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Drink Sales" ON boom_drink_sales FOR SELECT USING (true);
CREATE POLICY "Admin All Drink Sales" ON boom_drink_sales USING (true) WITH CHECK (true);

-- 5. DATOS INICIALES - PRODUCTOS POPULARES
TRUNCATE TABLE boom_products RESTART IDENTITY CASCADE;

INSERT INTO boom_products (name, category, price, image_url, stock, active, description) VALUES
-- Cocteles
('Cuba Libre Premium', 'coctel', 15.00, 'https://img.freepik.com/fotos-premium/coctel-cuba-libre-vaso-highball-hielo-cascara-lima-paja-limas-frescas-sobre-fondo-negro-mesa_157173-3330.jpg', 100, true, 'Ron + Coca Cola + limón'),
('Mojito Clásico', 'coctel', 18.00, 'https://cdn.craft.cloud/224393fa-1975-4d80-9067-ada3cb5948ca/assets/detail_Skinny_Mojito_4_2022.jpg', 100, true, 'Ron blanco, menta fresca y lima'),
('Margarita', 'coctel', 20.00, 'https://images.unsplash.com/photo-1544145945-f90425340c7e?q=80&w=1887&auto=format&fit=crop', 100, true, 'Tequila, triple sec y limón'),
('Tequila Sunrise', 'coctel', 18.00, 'https://exoticotequila.com/wp-content/uploads/2018/03/TEQUILA_SUNRISE_RC.jpg', 100, true, 'Tequila, jugo de naranja y granadina'),
('Gin Tonic', 'coctel', 22.00, 'https://licoreria247.pe/wp-content/uploads/2020/12/Vodka-vs-Gin.jpg.webp', 100, true, 'Gin premium, tónica y botánicos'),
('Calientito de Maracuyá', 'coctel', 12.00, 'https://polleriaslagranja.com/wp-content/uploads/2022/10/La-Granja-Real-Food-Chicken-Jarra-de-Maracuya.png', 100, true, 'Maracuyá, limón, whisky, azúcar'),

-- Licores
('Flor de Caña + Coca Cola', 'licor', 25.00, 'https://images.rappi.pe/products/237008-1575927253771.png', 50, true, 'Flor de caña premium + Coca Cola'),
('Old Time + Guarana', 'licor', 20.00, 'https://images.rappi.pe/products/1727659843457_1727659639313_1727659637802.jpg', 50, true, 'Old time + Guarana'),
('Whisky Sour', 'coctel', 25.00, 'https://so-sour.com/wp-content/uploads/2024/08/Whisky-Sour.jpg', 100, true, 'Whisky, limón y jarabe de goma'),

-- Shots
('Shot de Cortesía', 'shot', 0.00, 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=2070&auto=format&fit=crop', 200, true, 'Shot gratis para clientes VIP'),
('Shot de Tequila', 'shot', 8.00, 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=2070&auto=format&fit=crop', 200, true, 'Tequila premium'),

-- Cervezas
('Cerveza Pilsen', 'cerveza', 8.00, 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=2070&auto=format&fit=crop', 300, true, 'Cerveza nacional'),
('Cerveza Cusqueña', 'cerveza', 10.00, 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=2070&auto=format&fit=crop', 300, true, 'Cerveza premium peruana');

-- ============================================
-- SCRIPT COMPLETADO
-- Ejecuta este script en Supabase SQL Editor
-- ============================================
