-- Copy this SQL into your Supabase SQL Editor

-- Create the sales table with payment approval system
CREATE TABLE boom_sales_2026 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  dni TEXT,
  ticket_name TEXT NOT NULL,
  ticket_price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,
  total_amount NUMERIC NOT NULL,
  
  -- Payment Approval System
  payment_method TEXT DEFAULT 'yape', -- 'yape' or 'efectivo'
  payment_proof TEXT, -- Base64 encoded image (for Yape payments)
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  rejection_reason TEXT, -- Optional reason for rejection
  approved_at TIMESTAMPTZ, -- When the order was approved
  approved_by TEXT -- Admin who approved (for future use)
);

-- Enable Row Level Security (RLS)
ALTER TABLE boom_sales_2026 ENABLE ROW LEVEL SECURITY;

-- Create policies (Simplistic for demo: Allow anonymous inserts, but only authenticated reads/selects)
-- Note: For a real production app, you'd handle payment webhooks server-side.

-- Allow anyone to insert a sale (Public)
CREATE POLICY "Enable insert for everyone" ON boom_sales_2026 FOR INSERT WITH CHECK (true);

-- Allow select only for service role or specific users (For this demo, we might just allow anon read if we depend on client-side admin, 
-- BUT for security in a real Admin panel, we should restrict this. 
-- Since we are doing client-side Admin with a hardcoded password for the demo, we'll allow public read for now but warn about it).
-- IDEALLY: You should use Supabase Auth for the Admin panel.
CREATE POLICY "Enable select for everyone" ON boom_sales_2026 FOR SELECT USING (true);

-- Allow update for everyone (DEMO ONLY - for admin approval/rejection)
CREATE POLICY "Enable update for everyone" ON boom_sales_2026 FOR UPDATE USING (true);

-- Allow delete for everyone (DEMO ONLY - DO NOT USE IN PRODUCTION)
CREATE POLICY "Enable delete for everyone" ON boom_sales_2026 FOR DELETE USING (true);
